name: Mirror to repo-target (with accurate sync and deletions)

on:
  push:
    branches:
      - main
  delete:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo-source
        uses: actions/checkout@v3

      - name: Set up SSH and clone repo-target
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git clone git@github.com:nrk8008/repo-target.git target-repo

      - name: Sync files to target-repo (exclude mirror workflow)
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github/workflows/mirror.yml' \
            "$GITHUB_WORKSPACE"/ target-repo/

      - name: Commit and push changes
        run: |
          cd target-repo
          git add -A  # Stage deletions too
          if ! git diff --cached --quiet; then
            git commit -m "Mirror update from repo-source"
            git push origin main
          else
            echo "No changes to commit"
          fi
